### ISSUE TITLE
Fix alignment issues on mobile

### ISSUE THREAD

**Issue by bartjkdp** [VNG-Realisatie/nlx.io#4] opened 2018-09-10 11:08 UTC
The mobile version has some alignment issues.

![image](https://user-images.githubusercontent.com/5213690/45294098-8f12d580-b4fa-11e8-9cca-7bee4768e44e.png)

**Comment by dmijatovic** [comment] 2018-10-10 09:14
The issue is addressed in commit e14f8bf4fe57b074805d2e9db74349be52e2b109

**Closed by dmijatovic** 2018-10-10 09:14 UTC
